[tool.poetry]
name = "locust_qa_framework"
version = "0.1.0"
description = ""
authors = []
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
locust = "^2.33.0"
aiomysql = "0.2.0"
annotated-types = "0.7.0"
anyio = "4.13.0"
asyncpg = "0.31.0"
certifi = "2026.4.22"
classutilities = "0.2.1"
greenlet = "3.2.5"
h11 = "0.16.0"
httpcore = "1.0.9"
httpx = "0.27.0"
idna = "3.15"
jsonschema = "4.26.0"
jsonschema-specifications = "2025.9.1"
pydantic = "2.13.4"
pydantic-settings = "2.4.0"
pydantic-core = "2.46.4"
pymysql = "1.1.1"
python-dotenv = "1.0.1"
referencing = "0.37.0"
rpds-py = "0.30.0"
sniffio = "1.3.1"
sqlalchemy = "2.0.32"
sqlmodel = "0.0.21"
typing-inspection = "0.4.2"
typing-extensions = "4.15.0"
ruff = "^0.15.20"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py312"
line-length = 120

extend-exclude = [
    "example/excluded/folder/*"
]

[tool.ruff.lint]
select = [
    "F",      # Pyflakes (ошибки, неиспользуемый код)
    "E", "W", # pycodestyle (стандартные правила PEP 8)
    "I",      # isort (автоматическая сортировка импортов)
    "N",      # pep8-naming (правильный регистр для классов, функций, переменных)
    "UP",     # pyupgrade (принудительно переводит код на синтаксис новой версии Python)
    "B",      # flake8-bugbear (находит скрытые баги и потенциальные проблемы)
    "A",      # flake8-builtins (запрещает затенять встроенные функции, например, создавать переменную list=...)
    "C4",     # flake8-comprehensions (оптимизация генераторов списков и словарей)
    "RET",    # flake8-return (проверяет логику return, убирает лишние else)
    "SIM",    # flake8-simplify (помогает писать код проще, убирая громоздкие конструкции)
    "ARG",    # flake8-unused-arguments (находит неиспользуемые аргументы в функциях)
    "ERA",    # eradicate (находит и заставляет удалять забытый закомментированный код)
    "RUF",    # Собственные правила Ruff
]

ignore = [
    "E501",    # Игнорирует длину строки линтера, так как за этим следит `ruff format`
    "ERA001",  # игнорирует наличие комментариев
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]    # Игнорирует неиспользуемые импорты в init-файлах

[tool.poetry-exec-plugin.commands]
"lint" = "ruff check ."
"lint:fix" = "ruff check . --fix && ruff format ."
